//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCCSuaUrgenciaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalEspecialidade
    {
        public int IdHospital { get; set; }
        public int IdEspecialidade { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFim { get; set; }
        public bool Disponibilidade { get; set; }
        public int id { get; set; }
    
        public virtual Especialidade Especialidade { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
