//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCCSuaUrgenciaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital()
        {
            this.HospitalEspecialidade = new HashSet<HospitalEspecialidade>();
            this.Medico = new HashSet<Medico>();
            this.usuarioHospital = new HashSet<usuarioHospital>();
        }
    
        public int IdHospital { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public decimal Latidude { get; set; }
        public decimal Longitude { get; set; }
        public string Telefone { get; set; }
        public string Telefone2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalEspecialidade> HospitalEspecialidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medico> Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioHospital> usuarioHospital { get; set; }
    }
}
