//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCCSuaUrgenciaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioHospital
    {
        public int id { get; set; }
        public Nullable<int> idHospital { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
